// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoyPhNLrm4xN_XfloTVVV6j9x7k79y7sY',
    appId: '1:604438073588:web:3269faed16b206deef4ea1',
    messagingSenderId: '604438073588',
    projectId: 'krono-73e0e',
    authDomain: 'krono-73e0e.firebaseapp.com',
    storageBucket: 'krono-73e0e.firebasestorage.app',
    measurementId: 'G-FNQCHKJKZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ksMOdxja0keat1eOV88pyPxnonDRCzQ',
    appId: '1:604438073588:android:e34bbdac98b63d12ef4ea1',
    messagingSenderId: '604438073588',
    projectId: 'krono-73e0e',
    storageBucket: 'krono-73e0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2POhJXVZkOpvuBcBaQJ_tkLPF77EwSKg',
    appId: '1:604438073588:ios:7453f3d5404a296eef4ea1',
    messagingSenderId: '604438073588',
    projectId: 'krono-73e0e',
    storageBucket: 'krono-73e0e.firebasestorage.app',
    iosBundleId: 'com.example.krono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2POhJXVZkOpvuBcBaQJ_tkLPF77EwSKg',
    appId: '1:604438073588:ios:7453f3d5404a296eef4ea1',
    messagingSenderId: '604438073588',
    projectId: 'krono-73e0e',
    storageBucket: 'krono-73e0e.firebasestorage.app',
    iosBundleId: 'com.example.krono',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoyPhNLrm4xN_XfloTVVV6j9x7k79y7sY',
    appId: '1:604438073588:web:7205df2163dcc78cef4ea1',
    messagingSenderId: '604438073588',
    projectId: 'krono-73e0e',
    authDomain: 'krono-73e0e.firebaseapp.com',
    storageBucket: 'krono-73e0e.firebasestorage.app',
    measurementId: 'G-YVHXJ9QGFX',
  );
}
